; EXPLANATION
; main, sidebar, player, misc = background
; card                  = cards, tracklist, dropdowns, input fields background
; shadow                = text on button, tab active & selected row
; subtext               = playlist sidebar text, artist name, album name, tracklist number etc.
; selected row          = selected song & tab
; button-active         = play button, outline on focused input
; button                = all other buttons
; button-disabled       = volume & seekbar background, scrollbar handle, borders, hover

[wallpaper]
text               = d8cfc7
subtext            = d8cfc7
main               = 1b263a
sidebar            = 1b263a
player             = 1b263a
card               = 64676e
shadow             = ada7a3
selected-row       = 7b97b7
button             = 7b97b7
button-active      = 7b97b7
button-disabled    = 64676e
tab-active         = 7b97b7
notification       = 64676e
notification-error = eb6f92
misc               = 1b263a