[colors]
ansi = [
    '#1b263a',
    '#3d7bbc',
    '#697b87',
    '#8ba6bc',
    '#64676e',
    '#6179a0',
    '#657b8e',
    '#d1c7bd',
]
background = '1b263a'
brights = [
    '#888789',
    '#7b97b7',
    '#404754',
    '#64676e',
    '#ada7a3',
    '#d8cfc7',
    '#687997',
    '#dfd8d1',
]
cursor_bg = '#d1c7bd'
cursor_border = '#d1c7bd'
cursor_fg = '#1b263a'
foreground = '#d1c7bd'
selection_bg = '#64676e'
selection_fg = '#d1c7bd'

[colors.indexed]

[metadata]
name = 'Generated'