[colors]
ansi = [
    '#162933',
    '#a76760',
    '#3d7bbc',
    '#5d7d8a',
    '#5d6b6b',
    '#4978c4',
    '#2c8298',
    '#c8cdbf',
]
background = '162933'
brights = [
    '#818b87',
    '#9f764e',
    '#3a4a4f',
    '#5d6b6b',
    '#a4aca3',
    '#d0d4c9',
    '#31a9b5',
    '#d8dcd2',
]
cursor_bg = '#c8cdbf'
cursor_border = '#c8cdbf'
cursor_fg = '#162933'
foreground = '#c8cdbf'
selection_bg = '#5d6b6b'
selection_fg = '#c8cdbf'

[colors.indexed]

[metadata]
name = 'Generated'