[colors]
ansi = [
    '#222632',
    '#bf5955',
    '#0a83d3',
    '#cd9d49',
    '#6a686d',
    '#6b74b1',
    '#eebb6b',
    '#d7cbc6',
]
background = '222632'
brights = [
    '#8e898b',
    '#4173e2',
    '#46474f',
    '#6a686d',
    '#b3aaa9',
    '#ddd3cf',
    '#5296cf',
    '#e3dbd7',
]
cursor_bg = '#d7cbc6'
cursor_border = '#d7cbc6'
cursor_fg = '#222632'
foreground = '#d7cbc6'
selection_bg = '#6a686d'
selection_fg = '#d7cbc6'

[colors.indexed]

[metadata]
name = 'Generated'